### ISSUE TITLE
BeatFX needs some love

### ISSUE THREAD

**Issue by timewasternl** [timewasternl/Pioneered#1]
The section currently looks pretty empty (and uses hacky ways to simplify the Mixxx flow)

**Comment by bencejuhaasz** [comment]
I implemented a separate equalizer for the beatfx section: https://github.com/bencejuhaasz/Pioneered-Plus , so you can apply for eg. an echo only on mid&highs without making your mix messy with the heavy bass echoing during a drop.
This adds an important bit from the DJM-900 functionality. But
1) there are still a lot of effects missing
2) there is no parameter control
3) I don't know if we need bpm control on the beatfx like there is on the mixers

for 2), my idea is to use shift+track select, since this is the only "infinite turn" potentiometer on the DDJ-400.

**Comment by timewasternl** [comment]
Marvellous work and nice theming.
Although I understand the issues we still need to overcome, but I think there are some proposed changes in the DDJ-400 mapping in the Mixxx repo (for example https://github.com/mixxxdj/mixxx/pull/4662) that might stir the controller mapping up regarding the Beat FX. Maybe it's best to sit that one out before we will implement proper parameter control.
I personally don't think shift+track select would be very intuitive. Also, it is out of scope for a skin as it would be mapping behaviour.

Nevertheless, thanks again for your great work. Will merge!
