### ISSUE TITLE
bold or underline songs already played in a set

### ISSUE THREAD

**Issue by Sheyk90** [timewasternl/Pioneered#13]
Would it be possible to add the feature so that each song played in a set is marked or underlined like the xdj-rx does?
Thank you ;)

**Comment by bvobart** [comment]
Hmmmm I'm afraid that's not possible. The Library view is a component provided completely by Mixxx and while we can do some styling on it, I haven't been able to get a row in this view (i.e. a song) to have a different background color, underlined, whatever.

There is, however, a checkbox in the 'Played' column which shows whether you've played it since Mixxx started and how often you've played it since including it in your library. I noticed that is not very clearly styled, these are its default unchecked and checked states on my machine (probably influenced by my desktop's Qt theme as the pink line is).

![Screenshot_20221117_225755](https://user-images.githubusercontent.com/9915124/202568768-95b2ea59-8340-482d-a199-7a7a06e3f39f.png)
![Screenshot_20221117_225805](https://user-images.githubusercontent.com/9915124/202568769-57ec969f-ac80-477a-94dd-1160fe63617a.png)

Using `#LibraryWrapper WTrackTableView::indicator:unchecked` and `#LibraryWrapper WTrackTableView::indicator:checked`, we can fix those styles so they're a bit clearer and more in line with the theme (note: inspiration taken from Deere theme):

![Screenshot_20221117_230608](https://user-images.githubusercontent.com/9915124/202570102-635aeb20-7bca-41b4-ad3c-19717f06c4cc.png)
![Screenshot_20221117_230633](https://user-images.githubusercontent.com/9915124/202570106-db18575d-0f24-4899-a831-02283c7b8304.png)

That's about as much as I can do to my knowledge. As far as I know, it is not possible to style the whole row based on whether a certain QSS component is in a specific state, except in code or maybe if the library component was completely ours.

I'll make a PR with this. Hopefully that'll make it a bit clearer what songs you've already played.

**Comment by moretocome** [comment]
> Hmmmm I'm afraid that's not possible. The Library view is a component provided completely by Mixxx and while we can do some styling on it, I haven't been able to get a row in this view (i.e. a song) to have a different background color, underlined, whatever.
> 
> There is, however, a checkbox in the 'Played' column which shows whether you've played it since Mixxx started and how often you've played it since including it in your library. I noticed that is not very clearly styled, these are its default unchecked and checked states on my machine (probably influenced by my desktop's Qt theme as the pink line is).
> 
> ![Screenshot_20221117_225755](https://user-images.githubusercontent.com/9915124/202568768-95b2ea59-8340-482d-a199-7a7a06e3f39f.png) ![Screenshot_20221117_225805](https://user-images.githubusercontent.com/9915124/202568769-57ec969f-ac80-477a-94dd-1160fe63617a.png)
> 
> Using `#LibraryWrapper WTrackTableView::indicator:unchecked` and `#LibraryWrapper WTrackTableView::indicator:checked`, we can fix those styles so they're a bit clearer and more in line with the theme (note: inspiration taken from Deere theme):
> 
> ![Screenshot_20221117_230608](https://user-images.githubusercontent.com/9915124/202570102-635aeb20-7bca-41b4-ad3c-19717f06c4cc.png) ![Screenshot_20221117_230633](https://user-images.githubusercontent.com/9915124/202570106-db18575d-0f24-4899-a831-02283c7b8304.png)
> 
> That's about as much as I can do to my knowledge. As far as I know, it is not possible to style the whole row based on whether a certain QSS component is in a specific state, except in code or maybe if the library component was completely ours.
> 
> I'll make a PR with this. Hopefully that'll make it a bit clearer what songs you've already played.

Perhaps I'm stupid, but where do I find this? I can't see a played column in the library and it is not available in the right click menu either

**Comment by bvobart** [comment]
> Perhaps I'm stupid, but where do I find this? I can't see a played column in the library and it is not available in the right click menu either

Hmmmm that's strange, iirc right clicking on any of the column headers in the library allows you to select which columns you want to show. Can you share a screenshot of that selection menu? Do you see 'Played' in there somewhere?

If it's there and is already checked, maybe it's been moved all the way to the far left or right and scrolled out of view.
